spring.application.name=reconciliation
server.port=${SERVER_PORT:8084}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
account-service.base-url=${ACCOUNT_SERVICE_URL:http://localhost:8082}
management.endpoints.web.exposure.include=health,info
