spring.application.name=reconciliation
server.port=${SERVER_PORT:8084}
spring.datasource.url=${RECONCILIATION_DATABASE_URL:jdbc:postgresql://localhost:5432/reconciliation_db}
spring.datasource.username=${RECONCILIATION_DATABASE_USERNAME:aven}
spring.datasource.password=${RECONCILIATION_DATABASE_PASSWORD:aven}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
account-service.base-url=${ACCOUNT_SERVICE_URL:http://localhost:8082}
management.endpoints.web.exposure.include=health,info
